{
    'name': 'Odoo Studio for Community',
    'summary': 'Odoo Studio for Community',
    'version': '1.0',
    'category': 'Web',
    'description': """
        Odoo Studio. Customize and Build Odoo View on the fly without any technical knowledge
    """,
    'author': "medconsultantweb@gmail.com",
    'depends': ['web', "web_editor", "base_automation"],
    'data': [
        # 'views/templates.xml',
        'views/ir_ui_menu_view.xml',
        'views/report_kanban_view.xml',
        'security/view_dynamic_security.xml',
        'security/ir.model.access.csv',
    ],
    'qweb': [
        'static/src/xml/form_edit.xml',
        'static/src/xml/base.xml',
        'static/src/xml/form_fields.xml',
        'static/src/xml/kanban_template.xml',
        'static/src/xml/report_edit.xml',
    ],
    'assets': {
        'web.assets_qweb': [
            '/studio_for_community/static/src/js/navbar/nabar_view.xml',
            '/studio_for_community/static/src/xml/base.xml',
            '/studio_for_community/static/src/xml/form_edit.xml',
            '/studio_for_community/static/src/xml/form_fields.xml',
            '/studio_for_community/static/src/xml/kanban_template.xml',
            '/studio_for_community/static/src/xml/report_edit.xml',
        ],
        'web.assets_backend': [
            'studio_for_community/static/src/css/daterangepicker.css',
            'studio_for_community/static/src/scss/menu_edit.scss',
            'studio_for_community/static/src/scss/edit_view_controller.scss',
            'studio_for_community/static/src/scss/basic_field.scss',
            'studio_for_community/static/src/scss/list_edit.scss',
            'studio_for_community/static/src/scss/form_edit.scss',
            'studio_for_community/static/src/scss/calendar_edit.scss',
            'studio_for_community/static/src/scss/pivot_edit.scss',
            'studio_for_community/static/src/scss/kanban_edit.scss',
            'studio_for_community/static/src/scss/graph_edit.scss',
            'studio_for_community/static/src/scss/search.scss',
            'studio_for_community/static/src/scss/report.scss',
            'studio_for_community/static/src/js/libs/jquery.js',
            'studio_for_community/static/src/libs/daterangepicker.js',
            'studio_for_community/static/src/libs/jquery.stickytableheaders.js',
            'studio_for_community/static/src/js/views/list/list_renderer.js',
            'studio_for_community/static/src/js/views/search/search_view.js',
            'studio_for_community/static/src/js/views/form/form_view.js',
            'studio_for_community/static/src/js/views/form/form_controller.js',
            'studio_for_community/static/src/js/chrome/menu.js',
            # 'studio_for_community/static/src/js/chrome/abstract_web_client.js',
            'studio_for_community/static/src/js/widgets/data_export.js',
            'studio_for_community/static/src/js/widgets/model_field_selector.js',
            'studio_for_community/static/src/js/views/edit_views/automation_access/automations.js',
            'studio_for_community/static/src/js/views/edit_views/basic_fields.js',
            'studio_for_community/static/src/js/views/edit_views/edit_view.js',
            'studio_for_community/static/src/js/views/edit_views/list/list_edit.js',
            'studio_for_community/static/src/js/views/edit_views/list/list_content.js',
            'studio_for_community/static/src/js/views/edit_views/list/list_property.js',
            'studio_for_community/static/src/js/views/edit_views/form/form_edit.js',
            'studio_for_community/static/src/js/views/edit_views/form/form_content.js',
            'studio_for_community/static/src/js/views/edit_views/form/form_property.js',
            'studio_for_community/static/src/js/views/edit_views/calendar/calendar_edit.js',
            'studio_for_community/static/src/js/views/edit_views/calendar/calendar_content.js',
            'studio_for_community/static/src/js/views/edit_views/calendar/calendar_property.js',
            'studio_for_community/static/src/js/views/edit_views/pivot/pivot_edit.js',
            'studio_for_community/static/src/js/views/edit_views/pivot/pivot_content.js',
            'studio_for_community/static/src/js/views/edit_views/pivot/pivot_property.js',
            'studio_for_community/static/src/js/views/edit_views/graph/graph_edit.js',
            'studio_for_community/static/src/js/views/edit_views/graph/graph_content.js',
            'studio_for_community/static/src/js/views/edit_views/graph/graph_property.js',
            'studio_for_community/static/src/js/views/edit_views/kanban/kanban_edit.js',
            'studio_for_community/static/src/js/views/edit_views/kanban/kanban_content.js',
            'studio_for_community/static/src/js/views/edit_views/kanban/kanban_property.js',
            'studio_for_community/static/src/js/views/edit_views/report/ReportKanBan.js',
            'studio_for_community/static/src/js/views/edit_views/report/ReportContent.js',
            'studio_for_community/static/src/js/views/edit_views/report/ReportEdit.js',
            'studio_for_community/static/src/js/views/edit_views/report/ReportProperty.js',
            'studio_for_community/static/src/js/views/abstract_controller.js',
            'studio_for_community/static/src/js/views/base.js',
            'studio_for_community/static/src/js/views/edit_views/start.js',
            'studio_for_community/static/src/js/views/edit_views/studioEditor.js',
            'studio_for_community/static/src/js/views/edit_views/viewContainer.js',
            'studio_for_community/static/src/js/navbar/navbar.js',
        ],
    },
    'images': ['images/main_screen.jpg'],
    'price': 200,
    'license': 'OPL-1',
    'currency': 'EUR',
    'installable': True,
    'auto_install': False,
    'application': False,
    'images': [
        'static/description/module_image.jpg',
    ],
}
